program -> statement* EOF

statement -> block | letStmt | ifStmt | whileStmt | forStmt | fnDecl | exprStmt | callStmt

block -> "{" statement* "}"
exprStmt -> expr ";"
letStmt -> "let" IDENT "=" expr ";"
assignStmt -> IDENT "=" exprStmt
ifStmt -> "if" "(" expr ")" block ("elif" block)* ("else" block)?
whileStmt -> "while" "(" expr ")" block
forStmt -> "for" "(" letStmt expr ";" expr ")" bloc
fnDecl -> "fn" IDENT "(" params? ")" block
callStmt -> IDENT "(" params? ")"

expr -> equality
equality -> comparison (("!=" | "==") comparison)*
comparison -> term ((">" | "<" | ">=" | "<=") term)*
term -> factor ("+" | "-") factor
factor -> unary ("*" | "/") unary
unary -> "-" unary | "!" unary | primary
primary -> IDENT | NUMBER | STRING | "(" expr ")"

params -> "(" (expr ("," expr)*)? ")"



